### ISSUE TITLE
When I Join With ANY Version it say DISCONNECTED!!!

### ISSUE THREAD

**Issue by OneAddictions** [ProtocolSupport/ProtocolSupport#735]
When I Join in 1.8.8 it wont let me in it says Disconnected. (QUESTION: How do i disable versions from join!)

Server Log:
[20:14:26 WARN]: Failed to initialize a channel. Closing: [id: 0x3fabd1ce, L:/192.168.1.20:25567 - R:/192.168.1.20:49829]
java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
        at com.comphenix.protocol.events.ListeningWhitelist.toString(ListeningWhitelist.java:241) ~[?:?]
        at java.lang.String.valueOf(Unknown Source) ~[?:1.8.0_05]
        at java.lang.StringBuilder.append(Unknown Source) ~[?:1.8.0_05]
        at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:273) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:246) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:251) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:285) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:257) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printIterables(PrettyPrinter.java:144) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printValue(PrettyPrinter.java:277) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:246) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:124) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:102) ~[?:?]
        at com.comphenix.protocol.reflect.PrettyPrinter.printObject(PrettyPrinter.java:89) ~[?:?]
        at com.comphenix.protocol.error.DetailedErrorReporter.getStringDescription(DetailedErrorReporter.java:478) ~[?:?]
        at com.comphenix.protocol.error.DetailedErrorReporter.reportDetailed(DetailedErrorReporter.java:369) ~[?:?]
        at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:63) ~[?:?]
        at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:87) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$1.initChannel(NettyProtocolInjector.java:157) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:235) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:401) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:388) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector$2.initChannel(NettyProtocolInjector.java:167) [ProtocolLib.jar:3.7-SNAPSHOT-b232]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
[20:14:26 WARN]: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: null
        at net.minecraft.server.v1_12_R1.NetworkManager.close(NetworkManager.java:250) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
        at net.minecraft.server.v1_12_R1.NetworkManager.channelInactive(NetworkManager.java:106) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelInactive(LogicHandler.java:90) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelInactive(InitialPacketDecoder.java:91) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelInactive(SimpleReadTimeoutHandler.java:33) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:763) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
[20:14:26 WARN]: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NullPointerException: null
        at net.minecraft.server.v1_12_R1.NetworkManager.getRawAddress(NetworkManager.java:347) ~[spigot.jar:git-Spigot-5695bca-53fccdf]
        at protocolsupport.zplatform.impl.spigot.network.SpigotNetworkManagerWrapper.getRawAddress(SpigotNetworkManagerWrapper.java:48) ~[?:?]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelInactive(LogicHandler.java:97) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at protocolsupport.protocol.pipeline.initial.InitialPacketDecoder.channelInactive(InitialPacketDecoder.java:91) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelInactive(SimpleReadTimeoutHandler.java:33) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:763) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [spigot.jar:git-Spigot-5695bca-53fccdf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
>

**Comment by Shevchik** [comment]
Not a ProtocolSupport problem

**Comment by OneAddictions** [comment]
it is a protocolsupport problem!

**Comment by OneAddictions** [comment]
my server spigot works on 1.12 but when i add protocol support cause i want
1.8 players to join it dont work!

**Comment by Shevchik** [comment]
java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;
at com.comphenix.protocol.events.ListeningWhitelist.toString(ListeningWhitelist.java:241)
No it is not. Learn to read the exceptions logs.

**Comment by OneAddictions** [comment]
my server crashes when i add it with my other plugins but if i remove all
my plugins it works?! does it matter if i use 1.8 plugins? with 1.12.2
spigot?

**Comment by OneAddictions** [comment]
<--- MY PLUGINS
​

**Comment by ysl3000** [comment]
at com.comphenix.protocol.events.ListeningWhitelist.toString(ListeningWhitelist.java:241)

update protocollib to a stable version that is compatible to your servers version of mc.
